export function langOfLocaleIndex(localeIndex: string): string {
  return localeIndex === 'root' ? 'en' : localeIndex
}

export interface Labels {
  correct: string
  wrong: string
  review: string
  done: string
  mark: string
  commitLabel: string
  filesLabel: string
  edit: string
  add: string
  commit: string
  reset: string
  saved: string
  commitsLabel: string
  dirtyLabel: string
  taskLabel: string
  checkLabel: string
  taskPassed: string
  taskNotDone: string
  typeCommandLabel: string
  save: string
  cancel: string
  backToTop: string
  themeLabel: string
  theme: Record<'system' | 'light' | 'dark' | 'terminal' | 'retro', string>
}

export const LABELS: Record<string, Labels> = {
  en: {
    correct: 'Correct',
    wrong: 'Wrong',
    review: 'Review this lesson →',
    done: 'Lesson complete ✓',
    mark: 'Mark lesson complete',
    commitLabel: 'commit',
    filesLabel: 'Files',
    edit: 'Edit file',
    add: 'git add',
    commit: 'git commit',
    reset: 'Reset',
    saved: 'Saved as a commit ✓',
    commitsLabel: 'Commits',
    dirtyLabel: 'changes',
    taskLabel: 'Task',
    checkLabel: 'Check',
    taskPassed: 'Task complete ✓',
    taskNotDone: 'Task not complete yet',
    typeCommandLabel: 'Type a git command…',
    save: 'Save',
    backToTop: 'Back to top',
    themeLabel: 'Theme',
    theme: { 'system': 'System', 'light': 'Light', 'dark': 'Dark', 'terminal': 'Terminal', 'retro': 'Retro' },
    cancel: 'Cancel',
  },
  zh: {
    correct: '正确',
    wrong: '错误',
    review: '复习本课相关内容 →',
    done: '本课已完成 ✓',
    mark: '标记本课完成',
    commitLabel: '提交',
    filesLabel: '文件',
    edit: '编辑文件',
    add: 'git add',
    commit: 'git commit',
    reset: '重置',
    saved: '已保存为一次提交 ✓',
    commitsLabel: '提交',
    dirtyLabel: '改动',
    taskLabel: '任务',
    checkLabel: '检查',
    taskPassed: '任务完成 ✓',
    taskNotDone: '任务尚未完成',
    typeCommandLabel: '输入 git 命令…',
    save: '保存',
    backToTop: '回到顶部',
    themeLabel: '主题',
    theme: { 'system': '跟随系统', 'light': '浅色', 'dark': '深色', 'terminal': '终端', 'retro': '复古' },
    cancel: '取消',
  },
  ja: {
    correct: '正解',
    wrong: '不正解',
    review: 'この課の関連部分を復習 →',
    done: 'この課を完了 ✓',
    mark: '完了にする',
    commitLabel: 'コミット',
    filesLabel: 'ファイル',
    edit: 'ファイルを編集',
    add: 'git add',
    commit: 'git commit',
    reset: 'リセット',
    saved: 'コミットとして保存 ✓',
    commitsLabel: 'コミット',
    dirtyLabel: '変更',
    taskLabel: 'タスク',
    checkLabel: 'チェック',
    taskPassed: 'タスク完了 ✓',
    taskNotDone: 'まだ完了していません',
    typeCommandLabel: 'git コマンドを入力…',
    save: '保存',
    backToTop: 'トップへ戻る',
    themeLabel: 'テーマ',
    theme: { 'system': 'システム', 'light': 'ライト', 'dark': 'ダーク', 'terminal': 'ターミナル', 'retro': 'レトロ' },
    cancel: 'キャンセル',
  },
  ko: {
    correct: '정답',
    wrong: '오답',
    review: '이번 과의 관련 내용 복습 →',
    done: '이번 과 완료 ✓',
    mark: '완료로 표시',
    commitLabel: '커밋',
    filesLabel: '파일',
    edit: '파일 편집',
    add: 'git add',
    commit: 'git commit',
    reset: '초기화',
    saved: '커밋으로 저장됨 ✓',
    commitsLabel: '커밋',
    dirtyLabel: '변경',
    taskLabel: '과제',
    checkLabel: '확인',
    taskPassed: '과제 완료 ✓',
    taskNotDone: '아직 완료되지 않음',
    typeCommandLabel: 'git 명령어 입력…',
    save: '저장',
    backToTop: '맨 위로',
    themeLabel: '테마',
    theme: { 'system': '시스템', 'light': '라이트', 'dark': '다크', 'terminal': '터미널', 'retro': '레트로' },
    cancel: '취소',
  },
  de: {
    correct: 'Richtig',
    wrong: 'Falsch',
    review: 'Diese Lektion wiederholen →',
    done: 'Lektion abgeschlossen ✓',
    mark: 'Lektion abschließen',
    commitLabel: 'Commit',
    filesLabel: 'Dateien',
    edit: 'Datei bearbeiten',
    add: 'git add',
    commit: 'git commit',
    reset: 'Zurücksetzen',
    saved: 'Als Commit gespeichert ✓',
    commitsLabel: 'Commits',
    dirtyLabel: 'Änderungen',
    taskLabel: 'Aufgabe',
    checkLabel: 'Prüfen',
    taskPassed: 'Aufgabe erledigt ✓',
    taskNotDone: 'Noch nicht erledigt',
    typeCommandLabel: 'Git-Befehl eingeben…',
    save: 'Speichern',
    backToTop: 'Nach oben',
    themeLabel: 'Design',
    theme: { 'system': 'System', 'light': 'Hell', 'dark': 'Dunkel', 'terminal': 'Terminal', 'retro': 'Retro' },
    cancel: 'Abbrechen',
  },
  fr: {
    correct: 'Correct',
    wrong: 'Incorrect',
    review: 'Revoir cette leçon →',
    done: 'Leçon terminée ✓',
    mark: 'Marquer la leçon comme terminée',
    commitLabel: 'commit',
    filesLabel: 'Fichiers',
    edit: 'Modifier le fichier',
    add: 'git add',
    commit: 'git commit',
    reset: 'Réinitialiser',
    saved: 'Enregistré comme commit ✓',
    commitsLabel: 'commits',
    dirtyLabel: 'modifications',
    taskLabel: 'Tâche',
    checkLabel: 'Vérifier',
    taskPassed: 'Tâche terminée ✓',
    taskNotDone: 'Pas encore terminée',
    typeCommandLabel: 'Saisissez une commande git…',
    save: 'Enregistrer',
    backToTop: 'Retour en haut',
    themeLabel: 'Thème',
    theme: { 'system': 'Système', 'light': 'Clair', 'dark': 'Sombre', 'terminal': 'Terminal', 'retro': 'Rétro' },
    cancel: 'Annuler',
  },
  es: {
    correct: 'Correcto',
    wrong: 'Incorrecto',
    review: 'Repasar esta lección →',
    done: 'Lección completada ✓',
    mark: 'Marcar lección como completada',
    commitLabel: 'commit',
    filesLabel: 'Archivos',
    edit: 'Editar archivo',
    add: 'git add',
    commit: 'git commit',
    reset: 'Reiniciar',
    saved: 'Guardado como commit ✓',
    commitsLabel: 'commits',
    dirtyLabel: 'cambios',
    taskLabel: 'Tarea',
    checkLabel: 'Comprobar',
    taskPassed: 'Tarea completada ✓',
    taskNotDone: 'Aún no completada',
    typeCommandLabel: 'Escribe un comando git…',
    save: 'Guardar',
    backToTop: 'Volver arriba',
    themeLabel: 'Tema',
    theme: { 'system': 'Sistema', 'light': 'Claro', 'dark': 'Oscuro', 'terminal': 'Terminal', 'retro': 'Retro' },
    cancel: 'Cancelar',
  },
  pt: {
    correct: 'Correto',
    wrong: 'Incorreto',
    review: 'Rever esta lição →',
    done: 'Lição concluída ✓',
    mark: 'Marcar lição como concluída',
    commitLabel: 'commit',
    filesLabel: 'Arquivos',
    edit: 'Editar arquivo',
    add: 'git add',
    commit: 'git commit',
    reset: 'Reiniciar',
    saved: 'Salvo como commit ✓',
    commitsLabel: 'commits',
    dirtyLabel: 'mudanças',
    taskLabel: 'Tarefa',
    checkLabel: 'Verificar',
    taskPassed: 'Tarefa concluída ✓',
    taskNotDone: 'Ainda não concluída',
    typeCommandLabel: 'Digite um comando git…',
    save: 'Salvar',
    backToTop: 'Voltar ao topo',
    themeLabel: 'Tema',
    theme: { 'system': 'Sistema', 'light': 'Claro', 'dark': 'Escuro', 'terminal': 'Terminal', 'retro': 'Retrô' },
    cancel: 'Cancelar',
  },
  ru: {
    correct: 'Верно',
    wrong: 'Неверно',
    review: 'Повторить этот урок →',
    done: 'Урок завершён ✓',
    mark: 'Отметить урок завершённым',
    commitLabel: 'коммит',
    filesLabel: 'Файлы',
    edit: 'Изменить файл',
    add: 'git add',
    commit: 'git commit',
    reset: 'Сбросить',
    saved: 'Сохранено как коммит ✓',
    commitsLabel: 'коммиты',
    dirtyLabel: 'изменения',
    taskLabel: 'Задание',
    checkLabel: 'Проверить',
    taskPassed: 'Задание выполнено ✓',
    taskNotDone: 'Задание ещё не выполнено',
    typeCommandLabel: 'Введите команду git…',
    save: 'Сохранить',
    backToTop: 'Наверх',
    themeLabel: 'Тема',
    theme: { 'system': 'Система', 'light': 'Светлая', 'dark': 'Тёмная', 'terminal': 'Терминал', 'retro': 'Ретро' },
    cancel: 'Отмена',
  }
}

export function labelsFor(lang: string): Labels {
  return LABELS[lang] ?? LABELS.en
}
